#AutoIt3Wrapper_Run_AU3Check=N

#include "..\..\..\au3pm\au3unit\Unit\assert.au3"
#include "..\..\..\DateTime.au3"

$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('Atlantic/Reykjavik')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('Europe/Lisbon')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('Africa/Casablanca')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('Africa/Dakar')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('Europe/Dublin')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('Europe/London')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('UTC')
assertTrue($d.utc)
assertTrue($d.isUtc())
$d = DateTime()
$d.setDate(2013, 1, 1)
$d.setTimezone('GMT')
assertTrue($d.utc)
assertTrue($d.isUtc())
