#AutoIt3Wrapper_Run_AU3Check=N

#include "..\..\..\au3pm\au3unit\Unit\assert.au3"
#include "..\..\..\DateTime.au3"

$d = DateTime()
$d.setDate(2017, 2, 28)
assertSame(5, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 27)
assertSame(5, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 26)
assertSame(4, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 20)
assertSame(4, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 19)
assertSame(3, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 13)
assertSame(3, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 12)
assertSame(2, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 6)
assertSame(2, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2017, 2, 1)
assertSame(1, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 1)
assertSame(1, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 2)
assertSame(2, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 5)
assertSame(2, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 8)
assertSame(2, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 9)
assertSame(3, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 29)
assertSame(5, $d.weekNumberInMonth)
$d = DateTime()
$d.setDate(2018, 7, 30)
assertSame(6, $d.weekNumberInMonth)
$d = DateTime()
